### ISSUE TITLE
준투 : 닉네임을 변경했지만 댓글 등록시 변경된 닉네임 반경 안됨

### ISSUE THREAD

**Issue by junseoparkk** [100-hours-a-week/5-judy-kim-community#10]
1. 닉네임 변경 (피자보이 -> 피자보이yoyoyo)
![image](https://github.com/100-hours-a-week/5-judy-kim-community/assets/98972385/4fd8a1e9-150d-41ba-a322-4aee27d912c3)

2. 댓글 등록시 이전 닉네임으로 표시
![image](https://github.com/100-hours-a-week/5-judy-kim-community/assets/98972385/5b4ba9d5-9396-463c-b2bc-369f434c4ec8)

3. 회원 정보 수정 페이지에선 바뀐 닉네임으로 표시

**Comment by junseoparkk** [comment]
뭐지 다시 정상 작동합니다 속도 이슌가봐요

**Comment by judy-kimsohui** [comment]
해결했습니당 ㅎㅎ 세션 정보 갱신을 안했네요
