### ISSUE TITLE
준투 : 회원 탈퇴 기능 동작하지 않는 문제

### ISSUE THREAD

**Issue by junseoparkk** [100-hours-a-week/5-judy-kim-community#12]
아무리 회원 탈퇴를 눌러도 아래 이미지 화면만 보입니다
새로고침을 해도 회원 탈퇴가 되지 않았고, 게시글 목록에도 글이 남아있습니다

![image](https://github.com/100-hours-a-week/5-judy-kim-community/assets/98972385/48b9c3bf-b0ef-46f8-b92f-9422c084f15b)

**Comment by judy-kimsohui** [comment]
아항 왜 안되지??? 다시 볼게요!!

**Comment by judy-kimsohui** [comment]
해결 완료~ 게시글과 댓글은 삭제 안되게 막아놨습니당
