### ISSUE TITLE
홍 : 공백 특수문자 닉네임

### ISSUE THREAD

**Issue by JiHongKim98** [100-hours-a-week/5-judy-kim-community#15]
공백 특수문자
"ㅤ" 로 가입이 가능합니다

![스크린샷 2024-05-14 오후 10 02 22](https://github.com/100-hours-a-week/5-judy-kim-community/assets/144337839/ee27bc53-93bb-4fcf-9982-5ea885998545)

+추가) 화면 색은 확장 프로그램으로 다크모드로 변경한 것 입니당

**Comment by judy-kimsohui** [comment]
감사합니다 ㅎㅎ 수정할게요! ><

**Comment by judy-kimsohui** [comment]
<img width="589" alt="image" src="https://github.com/100-hours-a-week/5-judy-kim-community/assets/83997634/f1717957-1cc6-4862-b75c-2007d1222394">
