### ISSUE TITLE
회원가입시 이메일 helper text

### ISSUE THREAD

**Issue by moolmin** [100-hours-a-week/5-judy-kim-community#2]
이슈 내용
이메일 주소 형식 맞게 입력했는데
* 올바른 이메일 형식을 입력해주세요. <- helper text가 그대로 남아있습니다.

이미지 및 영상, 링크 등을 첨부
![Screenshot 2024-05-14 at 9 27 46 PM](https://github.com/100-hours-a-week/5-judy-kim-community/assets/145218872/abb26f9c-64c9-453d-9f56-c38aef1ee416)

**Comment by judy-kimsohui** [comment]
감사합니다 ㅎㅎ

**Comment by judy-kimsohui** [comment]
<img width="440" alt="image" src="https://github.com/100-hours-a-week/5-judy-kim-community/assets/83997634/eb5203e2-0bff-4b48-829f-97def82c97b8">
확인이 어렵네요 ㅠ
