### ISSUE TITLE
준투 : 현재 로그인한 사용자가 아님에도 댓글에 글쓴이로 표시됨

### ISSUE THREAD

**Issue by junseoparkk** [100-hours-a-week/5-judy-kim-community#4]
현재 피자보이로 로그인했는데 무적준투에 `(글쓴이)` 로 표시되는 문제 발생

![image](https://github.com/100-hours-a-week/5-judy-kim-community/assets/98972385/3dedb9a8-16e4-4603-b48c-629e961d91b1)
![image](https://github.com/100-hours-a-week/5-judy-kim-community/assets/98972385/717ba74a-592b-4146-876b-e59e218dfaf6)

**Comment by judy-kimsohui** [comment]
아하 게시글 쓴 사람을 글쓴이라고 설정했는데 (나) 를 추가하던가 문구를 수정해야겠군여!

**Comment by junseoparkk** [comment]
아 그 뜻이었구나 제가 잘못 이해했나봐요

**Comment by judy-kimsohui** [comment]
<img width="589" alt="image" src="https://github.com/100-hours-a-week/5-judy-kim-community/assets/83997634/d792533b-a2b8-4147-b4d0-d5f7d26bc043">
완료~
