### ISSUE TITLE
댓글 수정시 댓글입력창 조절이슈

### ISSUE THREAD

**Issue by moolmin** [100-hours-a-week/5-judy-kim-community#5]
이슈 내용
게시글에서 댓글 수정할때 댓글 수정창 resize가 켜져있어서 사이즈를 다르게하면 댓글 수정/삭제 버튼도 같이 움직이게 됩니다

이미지 및 영상, 링크 등을 첨부
![Screenshot 2024-05-14 at 9 38 52 PM](https://github.com/100-hours-a-week/5-judy-kim-community/assets/145218872/75c38ea8-047a-49a2-8925-9c354fb67111)

**Comment by judy-kimsohui** [comment]
아하 ㅎㅎ 감사합니다~!! 수정할게용
