### ISSUE TITLE
제이미: 회원가입 수정완료 알림창이 계속 떠있음

### ISSUE THREAD

**Issue by yoouung** [100-hours-a-week/5-judy-kim-community#6]
이슈 내용
기능정의서에서 수정 완료 토스트는 `수정하기` 버튼을 눌렀을 때 잠깐 뜨는 알림창이라고 되어있는데,
현재 페이지에 계속 보여지고 있고 클릭 이벤트도 있는 것 같네용..!!

이미지 및 영상, 링크 등을 첨부
![image](https://github.com/100-hours-a-week/5-judy-kim-community/assets/78146904/286e31e3-e69a-4e4b-8efb-fa1643c7f7fb)
<img width="549" alt="image" src="https://github.com/100-hours-a-week/5-judy-kim-community/assets/78146904/40fc91bb-7127-40c4-a929-4edd74cbb432">

**Comment by judy-kimsohui** [comment]
감사합니당 수정해볼게요!

**Comment by judy-kimsohui** [comment]
토스트 메세지로 모두 수정했어요!
