### ISSUE TITLE
제이미: 헤더 제목 클릭 시 게시글 목록으로 이동

### ISSUE THREAD

**Issue by yoouung** [100-hours-a-week/5-judy-kim-community#7]
이슈 내용
헤더에 있는 제목 클릭 시 게시글 목록으로 이동하는 클릭 이벤트 추가하면 좋을 것 같아요!

이미지 및 영상, 링크 등을 첨부
![image](https://github.com/100-hours-a-week/5-judy-kim-community/assets/78146904/4bdaa701-7341-4050-a675-7cd5fe8f6da7)

**Comment by judy-kimsohui** [comment]
알겠습니닷 ㅎㅎ
